read.csv("household_power_consumption.txt")
fulldata <- read.csv("household_power_consumption.txt")
data1 <- subset(fulldata, Date %in%, c("1/2/2007", "2/2/2007"))
data1 <- subset(fulldata, Date %in% c("1/2/2007", "2/2/2007"))
fulldata <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data1 <- subset(fulldata, Date %in% c("1/2/2007", "2/2/2007"))
hist(data1$Global_active_power, main="Global Active Power", 
     xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
png("plot1.png", width=480, height=480)
dev.off()
png("Plot1.png", width=480, height=480)
dev.off()
dev.copy(png, "Plot1.png", width=480, height=480)
dev.off()
